---
- name: Fail when necessary variables are undefined
  fail:
    msg: Please make sure a variable called 'network' exists. See 'defaults/main.yml' for more information.
  when: not 'network' in hostvars[inventory_hostname]

- name: Ensure /etc/network/interfaces.d/ exists
  become: True
  file:
    path: /etc/network/interfaces.d
    state: directory

- name: Install required software
  become: True
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - iproute2
    - iproute2-doc
    - resolvconf

- name: Configure loopback interface
  become: True
  copy:
    src: lo
    dest: /etc/network/interfaces.d/lo
    owner: root
    group: root
    mode: 0644

- name: Configure normal interfaces
  become: True
  template:
    src: iface.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ hostvars[inventory_hostname]['network']['iface'] }}"
  when: 'iface' in hostvars[inventory_hostname]['network']

- name: Overwrite main network config file
  become: True
  copy:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: not network_squash_config

- name: Overwrite main network config file
  become: True
  assemble:
    src: /etc/network/interfaces.d
    dest: /etc/network/interfaces
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: network_squash_config
