---
- name: Ensure /etc/network/interfaces.d/ exists
  become: True
  file:
    path: /etc/network/interfaces.d
    state: directory
  when: "'network' in hostvars[inventory_hostname]"

- name: Install required software
  become: True
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - iproute2
    - iproute2-doc
    - resolvconf
  when: "'network' in hostvars[inventory_hostname]"

- name: Install bridge-utils (if necessary)
  become: True
  apt:
    name: bridge-utils
    state: present
  when:
    - "'network' in hostvars[inventory_hostname]"
    - "'bridge' in hostvars[inventory_hostname]['network']"

- name: Configure loopback interface
  become: True
  copy:
    src: lo
    dest: /etc/network/interfaces.d/lo
    owner: root
    group: root
    mode: 0644
  when: "'network' in hostvars[inventory_hostname]"

- name: Configure normal interfaces
  become: True
  template:
    src: iface.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ hostvars[inventory_hostname]['network']['iface'] }}"
  when:
    - "'network' in hostvars[inventory_hostname]"
    - "'iface' in hostvars[inventory_hostname]['network']"

- name: Configure bridge interfaces
  become: True
  template:
    src: bridge.j2
    dest: "/etc/network/interfaces.d/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ hostvars[inventory_hostname]['network']['bridge'] }}"
  when:
    - "'network' in hostvars[inventory_hostname]"
    - "'bridge' in hostvars[inventory_hostname]['network']"

- name: Overwrite main network config file
  become: True
  copy:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
    owner: root
    group: root
    mode: 0644
  when:
    - "'network' in hostvars[inventory_hostname]"
    - not network_squash_config

- name: Overwrite main network config file
  become: True
  assemble:
    src: /etc/network/interfaces.d
    dest: /etc/network/interfaces
    backup: yes
    owner: root
    group: root
    mode: 0644
  when:
    - "'network' in hostvars[inventory_hostname]"
    - network_squash_config
